// Generated by Wrangler on Sat Sep 07 2024 10:30:46 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types --experimental-include-runtime=./src/types/runtime.d.ts`

interface Env {
	session_store: KVNamespace;
	data_cache: KVNamespace;
	DB: D1Database;
}
