// Generated by Wrangler on Mon Nov 25 2024 20:46:59 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types --experimental-include-runtime=./src/types/runtime.d.ts`

interface Env {
	session_store: KVNamespace;
	data_cache: KVNamespace;
	locks: KVNamespace;
	AT_SHORTCODE: string;
	AT_USERNAME: string;
	AT_API_KEY: string;
	AWS_ACCESS_KEY_ID: string;
	AWS_SECRET_ACCESS_KEY: string;
	TWILIO_ACCOUNT_SID: string;
	TWILIO_AUTH_TOKEN: string;
	TWILIO_PHONE_NUMBER: string;
	DB: D1Database;
}
