// Generated by Wrangler on Sat Sep 14 2024 15:44:30 GMT+0000 (Greenwich Mean Time)
// by running `wrangler types --experimental-include-runtime=./src/types/runtime.d.ts`

interface Env {
	session_store: KVNamespace;
	data_cache: KVNamespace;
	locks: KVNamespace;
	AT_SHORTCODE: string;
	AT_USERNAME: string;
	AT_API_KEY: string;
	DB: D1Database;
}
